name: CLI Build

on:
  workflow_dispatch:
  push:
    tags:
      - "cli-v*"

jobs:
  publish:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { name: win_x64, os: windows-latest, runtime: win-x64, executable: AssetRipper.CLI.exe, archive: zip }
          - { name: win_arm64, os: windows-latest, runtime: win-arm64, executable: AssetRipper.CLI.exe, archive: zip }
          - { name: linux_x64, os: ubuntu-22.04, runtime: linux-x64, executable: AssetRipper.CLI, archive: tar }
          - { name: linux_arm64, os: ubuntu-22.04-arm, runtime: linux-arm64, executable: AssetRipper.CLI, archive: tar }
          - { name: mac_x64, os: macos-14, runtime: osx-x64, executable: AssetRipper.CLI, archive: tar }
          - { name: mac_arm64, os: macos-14, runtime: osx-arm64, executable: AssetRipper.CLI, archive: tar }

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.config.runtime }}
        working-directory: ./Source/AssetRipper.CLI/

      - name: List Files
        shell: bash
        run: ls -R ./Source/0Bins/AssetRipper.CLI/Release/

      - name: Archive (zip)
        if: ${{ matrix.config.archive == 'zip' }}
        run: |
          cd ./Source/0Bins/AssetRipper.CLI/Release/${{ matrix.config.runtime }}/publish/
          7z a "$GITHUB_WORKSPACE/AssetRipper.CLI_${{ matrix.config.name }}.zip" .
        shell: bash

      - name: Archive (tar)
        if: ${{ matrix.config.archive == 'tar' }}
        run: |
          cd ./Source/0Bins/AssetRipper.CLI/Release/${{ matrix.config.runtime }}/publish/
          tar -czf "$GITHUB_WORKSPACE/AssetRipper.CLI_${{ matrix.config.name }}.tar.gz" .
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: AssetRipper.CLI_${{ matrix.config.name }}
          path: |
            ./AssetRipper.CLI_${{ matrix.config.name }}.*

      - name: Release
        if: startsWith(github.ref, 'refs/tags/cli-v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./AssetRipper.CLI_${{ matrix.config.name }}.*
